name: telegram message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send message to group
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        args: The ${{ github.repository }} Run ${{ github.workflow }} ${{job.status}}. ${{github.sha}} ${{github.event.name}} on branch ${{github.ref}}.
    # - name: send message to admin
    #   uses: appleboy/telegram-action@master
    #   with:
    #     to: ${{ secrets.TELEGRAM_TO_ME }}
    #     token: ${{ secrets.TELEGRAM_TOKEN }}
    #     args: The ${{ github.repository }} Run ${{ github.workflow }} ${{job.status}}. ${{github.sha}} ${{github.event.name}} on branch ${{github.ref}}.